table _Measures
	lineageTag: f7765116-f874-463a-ae72-37efc9d4966c

	measure 'Total Clients' = count(users_data[id])
		formatString: #,0
		lineageTag: d4ee9cfe-e69e-487b-9609-a568958cd8d1

	measure 'Female Clients' = CALCULATE([Total Clients], users_data[gender] ="Female")
		formatString: #,0
		lineageTag: e2e009b1-f542-4492-b32d-8062f5414bb7

	measure 'Male Clients' = CALCULATE([Total Clients], users_data[gender]="Male")
		formatString: 0
		lineageTag: 2d1ae9c1-7804-4b17-be07-e868cb7e8b88

	measure 'Avg Age' = AVERAGE(users_data[current_age])
		formatString: 0
		lineageTag: 7cf0462c-377e-4d72-8bd3-856e9abe4a28

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Female Avg_age' = CALCULATE([Avg Age], 'users_data'[gender]="Female")
		formatString: 0
		lineageTag: 54e3b34e-4a30-4902-a85f-463f08cf23fc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Male Avg_age' = CALCULATE([Avg Age], 'users_data'[gender]="Male")
		formatString: 0
		lineageTag: 002e379c-7d8b-4b9f-9dfe-1caac07a5bd7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Avg Yearly_income' = AVERAGE(users_data[yearly_income])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bf9b5e4e-70c2-4688-84dd-d856d2009aaf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Max Yearly_income' = MAX(users_data[yearly_income])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3afae095-8ec1-4e51-933a-5c7462f22d30

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Min Yearly_income' = MIN(users_data[yearly_income])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3dd7cae5-f455-45e4-b6e5-a75f1e08ffb6

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Per_cap_income' = AVERAGE(users_data[per_capita_income])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 73ff96b2-fcb4-4ba8-ac2b-195374fe2d42

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Max Per_cap_income' = MAX(users_data[per_capita_income])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 77a8a0aa-58d9-4ce1-82cb-aa46a2cc8af1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Min Per_cap_income' = MIN(users_data[per_capita_income])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2643b3cd-73f7-4b3a-90a5-893be30ce99f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Label = "●●●"
		lineageTag: 837b9cf8-6ab9-497d-88ab-eb5ec354191b

	measure 'Total Debt' = SUM(users_data[total_debt])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Debt
		lineageTag: d06613ff-bdfa-49fb-bba8-0076c338faef

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total DTI' = ```
			
			var  Yearly_income = sum(users_data[yearly_income])
			return
			  DIVIDE([Total Debt], Yearly_income, 0) * 100 
			```
		displayFolder: _DTI
		lineageTag: 6bce9ee1-1aa1-418b-8a1d-5f7eba492bc1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Single Max Debt' = MAXX(users_data, users_data[total_debt])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Debt
		lineageTag: df903cc8-fcff-45f4-a34f-418a39a62002

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Single Min Debt' =
			MINX(
			    FILTER(users_data,users_data[total_debt]>0), users_data[total_debt])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Debt
		lineageTag: 82fcdb4b-500d-4685-a508-f4ba0f5285b1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Loan Risk Score' = AVERAGE(users_data[Risk Score])
		displayFolder: _Risk Score
		lineageTag: de1b8daa-182b-4f85-9bc8-8a4a3de2f864

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Single Max Risk Score' = MAXX(users_data, users_data[Risk Score])
		displayFolder: _Risk Score
		lineageTag: 9fded7f0-06fb-409b-8d16-b607de8732fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Single Min Risk Score' = MINX(users_data, users_data[Risk Score])
		displayFolder: _Risk Score
		lineageTag: bbf3c322-c2e4-4f46-9d2e-954f1fe3c3c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Single Max DTI' = MAXX(users_data,users_data[DTI])
		displayFolder: _DTI
		lineageTag: 7a17a0bc-aada-4026-bb48-7b227f39660d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Single Min DTI' = MINX(FILTER(users_data, users_data[DTI] >0),users_data[DTI])
		displayFolder: _DTI
		lineageTag: f2412652-105a-4373-9d04-366c72e6e8c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total transaction' = DISTINCTCOUNT(fact_transactions_data[id])
		formatString: 0
		displayFolder: _Transaction
		lineageTag: 2d4235c6-7e9e-4681-b804-6eb2166534e3

	measure 'Total $' = SUM(fact_transactions_data[amount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Transaction
		lineageTag: 8cd23e4e-dfbf-4bb9-8ef5-29a424045c77

	measure 'Failed transaction' = CALCULATE([Total transaction], fact_transactions_data[status]="Failed")
		formatString: 0
		displayFolder: _Transaction
		lineageTag: 0550bdac-874f-4efc-ac43-d47cb4ef6a50

	measure 'Pass transaction' = CALCULATE([Total transaction], fact_transactions_data[status]="Pass")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Transaction
		lineageTag: 21905c09-9e7c-462d-b482-0a2c32a39ad8

	measure 'Pass $' = CALCULATE([Total $], fact_transactions_data[status]="Pass")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Transaction
		lineageTag: 5140ff61-ad9e-493d-94ab-5003b5ed6b14

	measure 'Failed $' = CALCULATE([Total $], fact_transactions_data[status]="Failed")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: _Transaction
		lineageTag: a52720ec-f4d5-445e-aee0-972f73c52f74

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

