table 'dictionary (2)'
	lineageTag: 8f350ffd-e888-460c-b56c-46cb8725d093

	column Column1
		dataType: string
		lineageTag: 8d86b36d-88da-45f8-a579-28d4c9c53095
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 0d0b0211-b246-403a-9605-e39a157ea398
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'dictionary (2)' = m
		mode: import
		queryGroup: Dictionary
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Ador_Bank_DA\Aurora Bank\transactions_data.xlsx"), null, true),
				    dictionary_Sheet = Source{[Item="dictionary",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dictionary_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

