table 'dictionary (4)'
	lineageTag: 1ca08fb7-5fc4-41b5-8176-216e20cdb614

	column Column1
		dataType: string
		lineageTag: 2f87899b-d740-422f-915a-de69453dfeb2
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 8c672473-6429-4f0a-8d57-24dfb93b50f4
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'dictionary (4)' = m
		mode: import
		queryGroup: Dictionary
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Ador_Bank_DA\Aurora Bank\mcc_codes.xlsx"), null, true),
				    dictionary_Sheet = Source{[Item="dictionary",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dictionary_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

