table 'dictionary (3)'
	lineageTag: 33d0222c-cda6-4682-a448-ec681c06025a

	column Column1
		dataType: string
		lineageTag: 244803d6-b704-46de-821a-3c4c5348644a
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: de99e895-6daf-4160-9a96-dd210e2a551c
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition 'dictionary (3)' = m
		mode: import
		queryGroup: Dictionary
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Ador_Bank_DA\Aurora Bank\cards_data.xlsx"), null, true),
				    dictionary_Sheet = Source{[Item="dictionary",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dictionary_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

