table users_data
	lineageTag: 32265793-d0e5-4e0d-a400-4ccaf2ab9ba7

	column id
		dataType: int64
		formatString: 0
		lineageTag: 07b3ef45-55b3-4b4e-b381-cf77efe61cdf
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column current_age
		dataType: int64
		formatString: 0
		lineageTag: 5d2dbcb2-716f-4336-9a9d-16499f7d7c59
		summarizeBy: none
		sourceColumn: current_age

		annotation SummarizationSetBy = Automatic

	column retirement_age
		dataType: int64
		formatString: 0
		lineageTag: bccc6c58-12cf-4d55-a24a-abc9aa328c70
		summarizeBy: none
		sourceColumn: retirement_age

		annotation SummarizationSetBy = Automatic

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: 5f9854dd-2a24-4a98-a392-d819d446717d
		summarizeBy: none
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column birth_month
		dataType: int64
		formatString: 0
		lineageTag: c88e358f-9e29-4acf-b1fb-80c78738ad1b
		summarizeBy: none
		sourceColumn: birth_month

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: e6587c09-b3d0-437b-bfa3-d4a4e9108ee3
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: ecca581d-9dc9-4b81-9148-01e5faf76186
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: string
		lineageTag: 1a5e2407-0931-4ea6-83b1-2d3061b72f4c
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: aa02911c-fa93-40c0-9877-d99708a9000d
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column per_capita_income
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8ff54167-60f3-40a1-b305-5af716c7936f
		summarizeBy: none
		sourceColumn: per_capita_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column yearly_income
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 25e27646-da86-4bbc-a9cd-892a0adaea5e
		summarizeBy: none
		sourceColumn: yearly_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column total_debt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0e711e73-bff2-4cbe-8512-e9a362bff4fa
		summarizeBy: none
		sourceColumn: total_debt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column credit_score
		dataType: int64
		formatString: 0
		lineageTag: 11d6ba37-cc59-4cd0-a59d-84dc6426b85d
		summarizeBy: none
		sourceColumn: credit_score

		annotation SummarizationSetBy = Automatic

	column num_credit_cards
		dataType: int64
		formatString: 0
		lineageTag: 86c1afbd-fa66-4b1c-b0f7-e72a3fa9e399
		summarizeBy: none
		sourceColumn: num_credit_cards

		annotation SummarizationSetBy = Automatic

	column age_bucket =
			SWITCH(
			    TRUE(),
			    users_data[current_age] >= 18 && users_data[current_age] <= 20, "18-20",
			    users_data[current_age] >= 21 && users_data[current_age] <= 30, "21-30",
			    users_data[current_age] >= 31 && users_data[current_age] <= 40, "31-40",
			    users_data[current_age] >= 41 && users_data[current_age] <= 50, "41-50",
			    users_data[current_age] >= 51 && users_data[current_age] <= 60, "51-60",
			    users_data[current_age] >= 61 && users_data[current_age] <= 70, "61-70",
			    ">71"
			)
		lineageTag: cd41e1dc-d8dd-4857-8e8d-03dc340621f3
		summarizeBy: none
		sortByColumn: age_bucket_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column age_bucket_sort =
			SWITCH(
			    TRUE(),
			    users_data[current_age] >= 18 && users_data[current_age] <= 20, "1",
			    users_data[current_age] >= 21 && users_data[current_age] <= 30, "2",
			    users_data[current_age] >= 31 && users_data[current_age] <= 40, "3",
			    users_data[current_age] >= 41 && users_data[current_age] <= 50, "4",
			    users_data[current_age] >= 51 && users_data[current_age] <= 60, "5",
			    users_data[current_age] >= 61 && users_data[current_age] <= 70, "6",
			    "7"
			)
		lineageTag: 8ebe2aee-2f04-4e19-97c5-aab0e89bac03
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Actice Years' = users_data[retirement_age] - users_data[current_age]
		formatString: 0
		lineageTag: 9c8873ca-7e27-4b01-8f40-c9f996a2497c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Active_years_bucket =
			SWITCH(
			    TRUE(),
			    users_data[Actice Years] >= 0 && users_data[Actice Years] <= 15, "0-15 Years",
			    users_data[Actice Years] >= 16 && users_data[Actice Years] <= 30, "16-30 Years",
			    users_data[Actice Years] >= 31 && users_data[Actice Years] <= 45, "31-45 Years",
			    users_data[Actice Years] >= 46 && users_data[Actice Years] <= 57, "46-57 Years",
			    "Retired"
			)
		lineageTag: d8cdc297-9830-4c28-95b3-4bd21f3bfe75
		summarizeBy: none
		sortByColumn: Active_years_bucket_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Active_years_bucket_sort =
			SWITCH(
			    TRUE(),
			    users_data[Actice Years] >= 0 && users_data[Actice Years] <= 15, "1",
			    users_data[Actice Years] >= 16 && users_data[Actice Years] <= 30, "2",
			    users_data[Actice Years] >= 31 && users_data[Actice Years] <= 45, "3",
			    users_data[Actice Years] >= 46 && users_data[Actice Years] <= 57, "4",
			    "5"
			)
		lineageTag: ba7dc68b-bdbf-4caf-8d77-f3e2aca9cadd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column income_bucket =
			SWITCH(
			    TRUE(),
			    users_data[yearly_income] >= 1 && users_data[yearly_income] <= 50000, "Low Income",
			    users_data[yearly_income] > 50001 && users_data[yearly_income] <= 100000, "Middle Income",
			    users_data[yearly_income] > 100001, "High Income",
			    "Unknown"
			)
		lineageTag: 193e567e-93db-4f6c-bb40-e8e7981a2f86
		summarizeBy: none
		sortByColumn: income_bucket_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column income_bucket_sort =
			SWITCH(
			    TRUE(),
			    users_data[yearly_income] >= 1 && users_data[yearly_income] <= 50000, "1",
			    users_data[yearly_income] > 50001 && users_data[yearly_income] <= 100000, "2",
			    users_data[yearly_income] > 100001, "3",
			    "4"
			)
		lineageTag: 28372f5e-b469-48a9-97e3-75c29b9bc19e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Credit score category' =
			
			SWITCH(
			    TRUE(),
			    users_data[credit_score] >= 750 , "Excellent",
			    users_data[credit_score] >= 700 , "Good",
			    users_data[credit_score] >= 650 , "Fair",
			    users_data[credit_score] < 650 , "Poor",
			    "Unknown"
			)
		lineageTag: 18bb968f-d188-429f-be37-9e457bc490c6
		summarizeBy: none
		sortByColumn: 'Credit score category_sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Credit score category_sort' =
			
			SWITCH(
			    TRUE(),
			    users_data[credit_score] >= 750 , "1",
			    users_data[credit_score] >= 700 , "2",
			    users_data[credit_score] >= 650 , "3",
			    users_data[credit_score] < 600 , "4",
			    "5"
			)
		lineageTag: b5e4b499-f682-4d66-8140-52d72655fa62
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DTI = ```
			DIVIDE(users_data[total_debt],users_data[yearly_income]) * 100 
			```
		lineageTag: 693e4d19-1693-40be-8488-6397b8030e42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DTI Category' =
			SWITCH(
			    TRUE(),
			    users_data[DTI] < 30, "Low Risk",
			    users_data[DTI] >= 30 && users_data[DTI] < 50, "Menageable",
			    users_data[DTI] >= 50 && users_data[DTI] < 150, "Risky Border",
			    users_data[DTI] >= 150 && users_data[DTI] < 190, "High Risk",
			    "Severe Risk"
			)
		lineageTag: 983dd9cb-ad17-479a-b1ac-e27a88fce3b2
		summarizeBy: none
		sortByColumn: 'DTI Category_sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'DTI Category_sort' =
			SWITCH(
			    TRUE(),
			    users_data[DTI] < 30, "1",
			    users_data[DTI] >= 30 && users_data[DTI] < 50, "2",
			    users_data[DTI] >= 50 && users_data[DTI] < 150, "3",
			    users_data[DTI] >= 150 && users_data[DTI] < 190, "4",
			    "5"
			)
		lineageTag: 8c8b2aea-4774-4bd6-aa33-bc48d1f6d781
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Risk Score' = ```
			
			var Maxscore = MAXX(ALL(users_data), users_data[credit_score])
			VAR MaxYr = MAXX(ALL(users_data),users_data[Actice Years])
			var MaxYrIncome = MAXX(ALL(users_data),users_data[yearly_income])
			VAR MaxDebt = MAXX(ALL(users_data),users_data[total_debt])
			VAR MaxCard = MAXX(ALL(users_data), users_data[num_credit_cards])
			
			RETURN 
			(
			    DIVIDE(users_data[credit_score],Maxscore) * 20 +
			    DIVIDE(users_data[yearly_income],MaxYrIncome) * 25 +
			    (1-DIVIDE(users_data[total_debt], MaxDebt)) *25 +
			    (1-DIVIDE(users_data[num_credit_cards],MaxCard)) * 10 +
			    (DIVIDE(users_data[Actice Years], MaxYr)) * 20
			
			)
			
			
			```
		lineageTag: 087334f0-0af4-4157-bafc-ac654b14ea7b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition users_data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Ador_Bank_DA\Aurora Bank\users_data.xlsx"), null, true),
				    users_data_Sheet = Source{[Item="users_data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(users_data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"current_age", Int64.Type}, {"retirement_age", Int64.Type}, {"birth_year", Int64.Type}, {"birth_month", Int64.Type}, {"gender", type text}, {"address", type text}, {"latitude", type any}, {"longitude", type number}, {"per_capita_income", Currency.Type}, {"yearly_income", Currency.Type}, {"total_debt", Currency.Type}, {"credit_score", Int64.Type}, {"num_credit_cards", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

